version: "3.8"

services:
  backend:
    build: ./backend
    container_name: shipping-converter-backend
    ports:
      - "8000:8000"
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - DISCORD_TOKEN=${DISCORD_TOKEN:-}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID:-}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID:-}
    volumes:
      - ./uploads:/app/uploads
      - ./scripts:/app/scripts
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: shipping-converter-frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  uploads:

networks:
  app-network:
    driver: bridge
