services:
  shipping-converter:
    build: .
    container_name: shipping-converter-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env
    volumes:
      - ./app.py:/app/app.py
      - ./scripts:/app/scripts
      - ./templates:/app/templates
      - ./static:/app/static
      - ./uploads:/app/uploads
    command: ["flask", "run", "--host=0.0.0.0", "--reload"]
    restart: unless-stopped
