name: Docker Build and Save

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t shipping-converter .

    - name: Save Docker image to tar file
      run: |
        docker save shipping-converter -o shipping-converter.tar

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Create GitHub Release
      id: create_release
      run: |
        gh release create "v${{ github.run_number }}" shipping-converter.tar -t "Release ${{ github.run_number }}" -n "Automated release for build ${{ github.run_number }}"

    - name: Upload Docker image tar file to release
      run: |
        gh release upload "v${{ github.run_number }}" shipping-converter.tar