name: Docker Build and Save

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t shipping-converter .

    - name: Save Docker image to tar file
      run: |
        docker save shipping-converter -o shipping-converter.tar

    - name: Upload Docker image tar file
      uses: actions/upload-artifact@v3
      with:
        name: shipping-converter-tar
        path: shipping-converter.tar