name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Lint (if configured)
      continue-on-error: true
      run: |
        cd frontend
        npm run lint || echo "No lint script configured"

    - name: Type check (if configured)
      continue-on-error: true
      run: |
        cd frontend
        npm run typecheck || echo "No typecheck script configured"

    - name: Build
      run: |
        cd frontend
        npm run build

    - name: Test (if configured)
      continue-on-error: true
      run: |
        cd frontend
        npm run test || echo "No test script configured"

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Test Docker build
      run: |
        cd frontend
        docker build -t shipping-converter-frontend:test .
